language: php
services:
    - mysql
php:
    - 7.3
env:
    - CORE_BRANCH=master DB=mysql

matrix:
  include:
  - php: 7.2
    env: "DB=sqlite CORE_BRANCH=stable20"

before_install:
    - export PATH="$PWD/vendor/bin:$PATH"
    - phpunit --version
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh deck $CORE_BRANCH $DB
    - cd ../server
    - ./occ app:enable deck

before_script:
    - cd apps/deck

script:
    - composer install
    - make test-unit

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - cat ../../data/nextcloud.log

notifications:
  email: false
